[mypy]
# Указывает версию Python, для которой выполняется проверка типов.
python_version = 3.13

# Исключает указанные директории или файлы из проверки mypy.
# В данном случае исключаются тесты, виртуальные окружения и скрипты.
exclude = tests_frontend/*|env.*|venv.*|\
           .git/*|__pycache__/*|dist/*|build/*

# Включает цветной и более читаемый вывод ошибок.
pretty = True
show_error_context = true

# Игнорирует ошибки, связанные с отсутствующими импортами.
# Это полезно, если используются сторонние библиотеки без типов.
ignore_missing_imports = True

# Указывает mypy не выводить сообщения о проверке импортов.
follow_imports = silent

# Запрещает частично аннотированные определения (например, функции без типов для всех параметров).
disallow_incomplete_defs = true

# Запрещает неявное использование `Optional` (например, `arg: str = None` без явного указания `Optional[str]`).
no_implicit_optional = true

# Включает строгую проверку для `Optional` типов.
strict_optional = true

# Предупреждает о избыточных приведениях типов (например, `cast(int, x)` когда `x` уже имеет тип `int`).
warn_redundant_casts = true

# Предупреждает о неиспользуемых игнорированиях типов (например, `# type: ignore`, которое не нужно).
warn_unused_ignores = true

# Предупреждает о недостижимом коде.
warn_unreachable = true

# Включает строгую проверку равенства (например, запрещает сравнение `str` с `int`).
strict_equality = true

# Включает явное указание базовых пакетов для улучшения поддержки модулей.
explicit_package_bases = True

# Включает локальные частичные типы для улучшения вывода типов.
local_partial_types = True

# Предупреждает, если функция не возвращает значение, но это ожидается (например, забыт `return`).
warn_no_return = true

# Предупреждает о неиспользуемых конфигурациях в `mypy.ini`.
warn_unused_configs = true

# Запрещает наследование от классов с типом `Any`.
disallow_subclassing_any = true
